### PR TITLE
CU-862k1mttp - Send cloud-sql-proxy logs to stdout not stderr

### PR DESCRIPTION
**Pull request by sachams**
By default, all logs from cloud-sql-proxy get sent to stderr. This means all log entries gert turned into ERROR  logs in datadog. By setting the -log_debug_stdout=true flag, you can send non-errors to stdout and errors to stderr. See [this issue](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/551).

We should also consider upgrading from v1 to v2 proxy at some point.

### CODE REVIEW

**Comment by sachams** [comment]
@daaain @afamagln the process for testing looks a little involved! Any tips about the easiest way to test on `test`? Could I maybe piggy back on your PR @afamagln ?

**Comment by daaain** [comment]
Looks good! I guess the easiest way to test is to update the YAML in k8s 😅

To make it possible to deploy you need to manually increment the version and create the tarball in the `docs` directory which is the Helm chart repo. That would be `TAG=0.2.1 make package` as we're on `0.2.0` right now and I'm not sure if a new tag for the Docker image also needs to be pushed 🤔

But after that it should be just incrementing the version number in the Helmfile and doing a full deploy.

**Comment by daaain** [comment]
Oh, and there's also a [CHANGELOG](https://github.com/team-blaze/helm-sqlproxy-ssh-tunnel/blob/master/CHANGELOG)

**Comment by sachams** [comment]
Ah! I'll hack the yaml then! :-)

**Comment by sachams** [comment]
Cool that worked! 
image

**Comment by sachams** [comment]
If you can approve shall I just merge it in and @afamagln wanna rebase off master?

**Comment by daaain** [comment]
Wait, don't merge before creating a new package (see [above](https://github.com/team-blaze/helm-sqlproxy-ssh-tunnel/pull/1#issuecomment-1609056153)) and adding a note to the changelog 😅

**Comment by sachams** [comment]
CHANGELOG updated! Looks like I need to do `TAG 0.2.1 make all`? Any idea what perms I need?

```sh
it00207sonsmith:helm-sqlproxy-ssh-tunnel sms$ TAG=0.2.1 make all
docker build -f Dockerfile -t berylcc/sqlproxy-ssh-tunnel:0.2.1 .
[+] Building 4.4s (12/12) FINISHED                                                                                                                                         
docker push berylcc/sqlproxy-ssh-tunnel:0.2.1
The push refers to repository [docker.io/berylcc/sqlproxy-ssh-tunnel]
...
61f2871f545a: Waiting 
denied: requested access to the resource is denied
make: *** [push] Error 1
```

**Comment by daaain** [comment]
> CHANGELOG updated! Looks like I need to do `TAG=0.2.1 make all`? Any idea what perms I need?

Oof, that would be a Docker Hub account with access to `berylcc` org 😅 that said, it's possible to override the registry, [see here](https://github.com/team-blaze/helm-sqlproxy-ssh-tunnel/blob/master/Makefile#L3)

**Review by daaain — APPROVED** [review]

**Pull request merged**
